##Step 1 : Read the Data!

In [1]:
import numpy as np

data_file = 'makeSenseOfCensus.csv'
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [2]:
print("\nType of data: \n\n", type(data))


Type of data: 

 <class 'numpy.ndarray'>


##Step 2 : Append the Data

In [3]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]
np.concatenate((data,new_record), axis=0)

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

##Step 3 : Check if it's a young country or old country

In [4]:
age = np.array(data[:,0])
max_age=age.max()
min_age = age.min()
age_mean = age.mean()
age_std = age.std()
print('Max age = ',max_age)
print('Min age = ',min_age)
print('Mean age = ',age_mean)
print('Standard Deviation = ',age_std)

Max age =  90.0
Min age =  17.0
Mean age =  38.051
Standard Deviation =  13.342803266180612


##Step 4: Let's check the country's race distribution to identify the minorities

In [5]:
race = np.array(data[:,2])
mask0 = race==0
race_0 = race[mask0]
mask1 = race==1
race_1 = race[mask1]
mask2 = race==2
race_2 = race[mask2]
mask3 = race==3
race_3 = race[mask3]
mask4 = race==4
race_4 = race[mask4]
len0 = len(race_0)
len1 = len(race_1)
len2 = len(race_2)
len3 = len(race_3)
len4 = len(race_4)
race_dist = np.array([len0, len1, len2, len3, len4])
print(race_dist)
minority_race = race_dist.min()
print('Least population by race is ',minority_race)
print('The race with least population is race 3(Other)')

[ 10  27 110   6 847]
Least population by race is  6
The race with least population is race 3(Other)


##Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

In [6]:
z=[]
for i in range(len(data)):
  if data[i,0]>59:
    z.append(list(data[i]))

z=np.array(z)
working_hrs_sum = sum(z[:,6])
#print(working_hrs_sum)
senior_citizen_len = len(z)
avg_working_hours = working_hrs_sum/senior_citizen_len
print('Average working hours for senior citizens is ',avg_working_hours)

Average working hours for senior citizens is  32.69444444444444


##Step 6: Let's check that higher educated people have better pay in general.

In [7]:
x = []
for i in range(len(data)):
  if data[i,1]>10:
    x.append(list(data[i]))
high = np.array(x)
#print(high)
y = []
for i in range(len(data)):
  if data[i,1]<=10:
    y.append(list(data[i]))
low = np.array(y)

avg_pay_high = np.mean(high[:,7])
avg_pay_low =  np.mean(low[:,7])
print('Average pay for highly educated people: ',avg_pay_high)
print('Average pay for lower educated people: ',avg_pay_low)

Average pay for highly educated people:  0.42813455657492355
Average pay for lower educated people:  0.13670133729569092
